#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Write your code here
    ps=0
    ns=0
    zs=0
    for i in arr:
        if i>0:
            ps+=1
        elif i<0:
            ns+=1
        elif i==0:
            zs+=1
    s=len(arr)
    print(ps/s)
    print(ns/s)
    print(zs/s)
    
        

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
